apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: appservices.pocrolloutoperator.jewzaam.org
spec:
  group: pocrolloutoperator.jewzaam.org
  names:
    kind: AppService
    listKind: AppServiceList
    plural: appservices
    singular: appservice
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
